# 服务配置
server:
    port: 8080
    
# 英克正式库 默认数据源
spring:
    datasource.url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8
    datasource.username: root
    datasource.password: hejie1996
    datasource.driverClassName: com.mysql.jdbc.Driver
     
    datasource.initialSize: 5
    datasource.minIdle: 5
    datasource.maxActive: 20
    # 配置获取连接等待超时的时间
    datasource.maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    datasource.timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    datasource.minEvictableIdleTimeMillis: 300000
    datasource.validationQuery: SELECT 1 FROM DUAL
    datasource.testWhileIdle: true
    datasource.testOnBorrow: false
    datasource.testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    datasource.filters: stat,wall,log4j
    datasource.logSlowSql: true
    
    mvc:
        view:
            prefix : /
            suffix : .html
    
    #resources:
     #   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static

# mybatis的配置
mybatis:
    type-aliases-package: top.hjie.pojo
    mapper-locations: classpath:mybatis/*.xml

# 分页助手
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: 

# 日志输出
logging:
    level:
        top.hjie: debug